on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up PlatformIO
      uses: platformio/action-setup@v2
      with:
        python_version: '3.8'
    - name: Run tests on the native platform
      run: platformio test -e native